operators/tokenizer/bert_tokenizer.cc
operators/tokenizer/bert_tokenizer.hpp

- Reduce bert tokenize memory usage through saving the vocab from unorder_map<ustring, int32_t> -> unorder_map<string_view, int32_t>
- Before search the vocab table, ustring will be casted to std::string

Reduce bert tokenize memory usage

---

includes/ocos.h

Add ORT_API_CALL to AddExternalCustomOp so that the calling convention of the declaration in ocos.h matches the calling convention of the definition in ortcustomops.cc for x86 builds.

Add ORT_API_CALL to AddExternalCustomOp in ocos.h

---

ci_build/azure-pipelines/mshost.yaml
operators/tokenizer/blingfire_sentencebreaker.cc

`KernelBlingFireSentenceBreaker::Compute(OrtKernelContext* context)` from operators/tokenizer/blingfire_sentencebreaker.cc currently contains the following code:
```
int max_length = 2 * input_string.size() + 1;
std::string output_str;
output_str.reserve(max_length);
```
... however, `std::string::reserve` only reserves memory and does not resize `std::string` so the use of `output_str.data()` and the use of `output_str[i]` that follow are not defined ... and in a Debug build where bounds checking based on the size of `std::string` is done, `output_str[i]` fails.
Either of the following can be used instead:
```
std::string output_str;
output_str.resize(max_length, '\0'); // or just output_str.resize(max_length); since '\0' is implied.
```
... or:
```
std::unique_ptr<char[]> output_str = …
```

Correct memory indexing issue.

---

operators/tokenizer/sentencepiece_tokenizer.cc

Identified potential bug in SentencePieceTokenizer where encoding was
not restricted to specific token. Sentencepiece.Encode itself doesn't
clear the input vector before populating the result for the input
token.

Bug in SentencepieceTokenizer

---

requirements.txt

Similar to: https://github.com/onnx/onnx/pull/4223
We will need this change until onnx publishes a patch release to include the above change.

Update requirements.txt to restrict protobuf version

---

.config/tsaoptions.json

This is a follow-up to #297. The changes in #297 didn't work.  For unknown reason, we need to add this setting.

Update tsaoptions.json to explicitly set template name

---

cmake/externals/googlere2.cmake
cmake/externals/json.cmake

**Old Versions**:
json: v3.7.3
googlere2: 2020-11-01
**New Versions**:
json: v3.10.5
googlere2: 2021-06-01
**Validation**

Updated json and re2 version as per ort req

---

requirements-dev.txt

Include requirements.txt from requirements-dev.txt so that pip has context to avoid installing incompatible dependencies.
Fix the CI build.

Include requirements.txt from requirements-dev.txt.

---

.pipelines/ci.yml
.pipelines/wheels_linux.yml
.pipelines/wheels_macos.yml
.pipelines/wheels_win32.yml

Moving build definitions from `.az` to `.pipelines` in three parts:
- copy files from `.az` to `.pipelines` (this PR)
- update Azure DevOps pipelines to point to new files
- remove `.az`

Copy build definitions from `.az` to `.pipelines`

---

tools/add_pre_post_processing_to_model.py
tools/pre_post_processing/pre_post_processor.py
tools/pre_post_processing/steps/vision.py
tools/pre_post_processing/utils.py

Add ability to specify opset so we can easily adjust to the opset supported by the onnxruntime package.

Add ability to specify onnx opset when adding pre/post processing to model

---

cmake/externals/sentencepieceproject.cmake

Combined ORT + ort-ext build for Android fails due to protobuf mismatch. 
Move the setting of SPM_USE_BUILTIN_PROTOBUF to before the populate to fix.

Fix sentencepiece build error

---

CMakeLists.txt

I'm not sure what the purpose of `_ONNXRUNTIME_EMBEDDED` is, but the if branch checking it's existence in `ext_ortlib.cmake` uses the path `${CMAKE_SOURCE_DIR}/incluude/onnxruntime/core/session` to attempt to find libs and headers for ORT.
When using ` `${CMAKE_SOURCE_DIR}/../include/onnxruntime/core/session`, unless you have the ONNX library in located in `include/onnxruntime/core/session` above the project root (a bit of a random place?), it will fail to find headers and libs.
This will cause the variable `ONNXRUNTIME_PKG_DIR` to be ignored, but the user can set that variable to the root of ONNX runtime, causing it to actually find the lib.
My suggestion is to always use `${ONNXRUNTIME_PKG_DIR}` when defined, as users like myself, can pull prebuilt packages (or build from source), find …

Possible fix for "FetchContent" builds, always use ONNXRUNTIME_PKG_DIR when defined.

---

onnxruntime_extensions/tools/Example usage of the PrePostProcessor.md
tutorials/superresolution_e2e.py

Update tutorial and example usage to provide info on installing the nightly python package until the pypi package is available.

Update tutorial and example usage to provide info on installing the nightly python package

---

CMakeLists.txt
cmake/externals/json.cmake

Use dependency name 'nlohmann_json' which is the same name that ORT uses.
https://github.com/microsoft/onnxruntime/blob/4a676b011a71f5a1ddacdac566f5579f0e132976/cmake/external/onnxruntime_external_deps.cmake#L154-L159
Then the FetchContent calls in both ORT and ORT Extensions won't try to fetch this dependency as two separate dependencies and complain about an existing target created by the first fetch.

Fix ORT combined build nlohmann_json fetch.

---

.pipelines/wheels_linux.yml

In pool's settings, either you only specify the "name" attribute, or only "vmImage". The "Linux-CPU" was created by me, it only has one image. So your "vmImage" setting was ignored.

Update wheels_linux.yml: change the linux machine pool name

---

.pipelines/OneBranch.PullRequest.yml

CodeQL needs to be updated from Guardian to CodeQL 3000 Extension as Guardian is outdated, however the CodeQL 3000 Extension does not support PR or tag branches.
However, switching codeql option from `python` to `compiled` (as used here: https://onebranch.visualstudio.com/OneBranch/_wiki/wikis/OneBranch.wiki/6249/CodeQL-3000) automatically skips it in the pipeline, thus adding that instead of disabling completely.

Fix OneBranch PR pipeline CodeQL issue

---

CMakeLists.txt
cmake/ext_java.cmake
tools/android/build_aar.py

Link against the shared library in an Android build so libortextensions.so is available for nuget to use. 
Include libortextensions.so in the AAR
Cleanup some misc things.

Fix Android AAR in nuget package. Requires libortextensions.so.

---

onnxruntime_extensions/tools/pre_post_processing/pre_post_processor.py
test/data/ppp_vision/create_boxdrawing_model.py
test/data/ppp_vision/create_decode_encode_test_model.py
test/test_tools_add_pre_post_processing_to_model.py

Calculate and specify ir_version so we use the oldest possible for maximum compatibility.
Remove requirement for ONNX version < 1.14

Handle ONNX 1.14 in test scripts

---

onnxruntime_extensions/_cuops.py
operators/tokenizer/bert_tokenizer.cc
operators/tokenizer/bert_tokenizer.hpp
test/test_bert_tokenizer.py

Supports most basic sentences in En, Fr, De, Es, Cn, and Jp, given vocab handles tokens. Special or unknown tokens are not supported at the moment, as model training (the common use-case for offset mapping) does not usually include unknown tokens.
Validation:

Initial BertTokenizer offset mapping implementation

---

.pipelines/android_packaging.yml
.pipelines/ci.yml
.pipelines/templates/android-shared-lib-build.yml
.pipelines/templates/build-package-for-android-aar.yml
tools/utils/android.py

Pass `-gpu swiftshader_indirect` emulator args as a workaround to get Android emulator running on the MacOS 13 hosted agents.
See https://github.com/actions/runner-images/issues/7671

Move remaining MacOS 12 CI build agents to MacOS 13.

---

operators/tokenizer/bert_tokenizer.cc
operators/tokenizer/bert_tokenizer.hpp
operators/tokenizer/clip_tokenizer.cc
operators/tokenizer/clip_tokenizer.hpp
operators/tokenizer/roberta_tokenizer.cc
operators/tokenizer/roberta_tokenizer.hpp

Originally, there were some issues with simply using a C++ tokenizer class variable for skipping offset mapping computations as needed for BertTokenizer, so had to use global variable. CLIP and Roberta tokenizers were fine.

Add perf changes for Bert, CLIP and Roberta with offset mapping

---

includes/onnxruntime_extensions.h

Add ifdef for swift package manager support.
It requires a prefix for headers searching path.
Similarly as what we do for ORT C headers

Configure header path for SPM build

---

includes/custom_op_lite.h
test/shared_test/test_kernel.hpp
test/shared_test/test_ortops.cc
test/shared_test/test_ortops_strings.cc
test/shared_test/test_ortops_vision.cc
test/static_test/test_strings.cc
test/static_test/test_utils.cc

- ifdef out some test code that requires RE2 if RE2 is not enabled
- add ability to plugin custom output validator for C++ unit tests
- OpenAI responses can have different punctuation so we need to support allowing for that
-  used in the new unit tests that will be in the refactoring PR
- add comment to custom op lite to clarify that outputs are 'handled' by doing nothing

Split out some miscellaneous changes from refactoring the azure ops.

---

CMakeLists.txt
cmake/ext_java.cmake
includes/exceptions.h
includes/ocos.h
operators/azure/azure_triton_invoker.cc
operators/azure/cloud_base_kernel.cc
operators/azure/cloud_base_kernel.hpp
operators/azure/curl_invoker.cc
operators/azure/logger.hpp
prebuild/build_curl_for_android.sh
prebuild/build_curl_for_android_on_linux.patch
test/shared_test/test_ortops_azure.cc
tools/android/build_aar.py

- Ensure we log an error message before throwing on Android
- message in exception will be lost due to how the shared libraries are built (both onnxruntime and extensions use static libc++ so there are no shared exception types between them)
- support static or dynamic build of curl/openssl on android
- TBD which we want to use. static is smaller but build fails on x86 currently so might need a mix
- add infra for anything deriving from BaseKernel to log messages using the ORT logger
- ensures messages from custom kernels end up in the same place as messages from ORT

Android fixes/improvements

---

nuget/NativeNuget.nuspec
onnxruntime_extensions/_hf_cvt.py
tools/android/package_ops.config
tools/ios/package_ops.config

Most usage of this tokenizer is wrong, which causes some bugs.
The reason of 'CLIP' instead of 'Clip' is to align with HF's
https://github.com/huggingface/transformers/blob/36f183ebab1261b388739d628aaa0b4150068df0/src/transformers/models/clip/tokenization_clip_fast.py#L50

correct CLIP tokenizer name

---

tutorials/whisper_e2e.py

This PR fixes running this script by defining the number of mels and number of frames on separate lines.

Separate variable definition in Whisper E2E script

---

test/test_autotokenizer.py

only core tokenizer left without a test - added because current trending HF models are using it as well (top stabilityai models): https://huggingface.co/models?sort=trending

Add CLIPTokenizer test for AutoTokenizer

---

pyop/pyfunc.cc

PyCustomOpDef::AddOppyop/pyfunc.cc | Don't use std::move on constant variables. (es.56).

Update pyfunc.cc for the prefast warning.

---

onnxruntime_extensions/_cuops.py
operators/tokenizer/sentencepiece_tokenizer.cc
operators/tokenizer/sentencepiece_tokenizer.hpp
test/test_sentencepiece_ops.py

**Usage**: pass in value `true` for `add_bos`, `add_eos`, and new optional input boolean `fairseq` when creating SentencePieceTokenizer.
Validation:

Add support for Fairseq models (like XLMRobertaTokenizer)

---

.pipelines/wheels_linux.yml

Enable azure ops in linux whl packaging pipeline.

Enable azure ops in linux whl packaging pipeline

---

.pipelines/ci.yml
.pipelines/ios_packaging.yml

- Add separate step to wait for simulator to boot.
- Add -parallel-testing-enabled NO xcodebuild option.
Per suggestions from here:
https://github.com/fastlane/fastlane/issues/21025#issuecomment-1435665269
https://heartbeat.comet.ml/the-fast-furious-and-flaky-continuous-integration-with-xcode-10-parallel-tests-2da71fd48cb1

Address iOS CI build flakiness

---

CMakeLists.txt
base/noexcep_operators_placeholder.cc
operators/ocos_operators_placeholder.cc

When ONNX Runtime is built with the flags `--use_extensions` within a minimal build (reduced ops), some of the operators are not built within the `onnxruntime-extensions`.
For example, building onnx runtime with the flag `--cmake_extra_defines=OCOS_ENABLE_TF_STRING=ON` only expects the ocos string operators to be built and included. These operators are currently built inside the `noexcep_operators` and as a result `ocos_operators` library does not get built (as it has no valid sources).
However, onnxruntime takes a dependency on `ocos_operators` library (and now also on `noexcep_operators` library after https://github.com/microsoft/onnxruntime/pull/17850). Since `ocos_operators` library does not get built, it results in ONNX Runtime build failure as well.
This PR introduces placeholder …

Ensure noexcep_operators and ocos_operators get built always

---

operators/tokenizer/bpe_kernels.cc
operators/tokenizer/bpe_utils.hpp
requirements-dev.txt
test/test_autotokenizer.py
test/test_cliptok.py

fixes newline and apostrophe handling for issues discovered by long text testing.
**Update**: CLIPTokenizer tokenizes apostrophes separately (['you', ''', 're']) but CLIPTokenizerFast tokenizes together (['you', ''re']), **unless ftfy is installed**: https://github.com/huggingface/transformers/issues/22166.

Fix newline and apostrophe handling for BPE

---

requirements-dev.txt
test/test_autotokenizer.py
test/test_cliptok.py

ftfy is required for parity between CLIPTokenizer and CLIPTokenizerFast.

Remove ftfy imports and add warning if not installed

---

test/test_autotokenizer.py

Remove ftfy warning after latest HF Update fixes CLIP discrepancy

Remove ftfy warning after latest HF transformers update fixes CLIP discrepancy

---

CMakeLists.txt
cmake/ext_tests.cmake

How to test locally:
export CUDA_PATH=/usr/local/cuda-11.8
sh ./build.sh -DOCOS_ENABLE_CTEST=ON -DOCOS_ONNXRUNTIME_VERSION={ORT_VERSION} -DOCOS_USE_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES=86 -DONNXRUNTIME_PKG_DIR={ORT_RELEASE_DIR} 
Note:
1. Since std::filesystem is used in unit test, gcc version should be bigger than 9.0
2. CI pipeline will be enabled in next PR.

Make ort extensions build successfully on Linux GPU 

---

.pipelines/ci.yml
.pipelines/ci_optional.yml

ideally, all of jobs should be put it in one pipeline, but realistically, we move the unstable and volatile ones here to unblock PR submitting process.

Create a CI optional pipeline

---

.pipelines/android_packaging.yml

adding 30 mins to Android packaging pipeline timeout due to early timing out.

Increase Android packaging pipeline timeout

---

operators/tokenizer/sentencepiece_tokenizer.cc

This fixes #639 by moving the fairseq id patching out of the loop so it's not applied multiple times to sequences earlier in the batch.
I've added the check to ensure it's not applied when `add_rev` is true mirroring its position in the for loop, but I'm unsure if that's required (presumably there are no HF tokenizers which emit a reversed string and have this fairseq hack?).
I tested it against the example in #639 and both batches and single sequences work correctly now.

Fix batching in fairseq SentencepieceTokenizer

---

tools/ios/build_xcframework.py

Unit test helper uses std::filesystem which isn't available until iOS 13. #648 changed the default to enable tests. 
Nuget packaging pipeline is failing due to this.

Disable c++ tests on iOS build targeting iOS < 13.

---

onnxruntime_extensions/_cuops.py
onnxruntime_extensions/_hf_cvt.py
operators/tokenizer/bpe_decoder.hpp
operators/tokenizer/bpe_kernels.cc
operators/tokenizer/bpe_kernels.h
operators/tokenizer/bpe_tokenizer.hpp
operators/tokenizer/tokenizers.cc
test/test_autotokenizer.py
test/test_fast_tokenizer.py

Unify the spm/bpe tokenizers

---

.pipelines/templates/build-package-for-nuget.yml
.pipelines/templates/build-package-for-windows.yml

Onnxruntime dropped support for ARM32 in 1.17.1. Make corresponding changes here to keep the nuget pipeline happy.

Fix nuget pipeline for onnxruntime-extensions

---

.pipelines/java_packaging.yml

Successful test pipeline: https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=424674&view=results
Unzipped and ensured files for Windows, Linux, and MacOS are in the JAR and Windows binary is signed.
#597

Combine JAR Packages for Windows, Linux, and MacOS

---

base/ortx_common.h
base/string_utils.h
docs/development.md
includes/custom_op_lite.h
includes/onnxruntime_cpp_api_legacy.hpp
includes/onnxruntime_customop.hpp
includes/onnxruntime_no_customop.h
operators/contrib/cuda/cuda_type.h
operators/contrib/cuda/device_prop.cuh
operators/contrib/cuda/fast_gelu.h
operators/contrib/cuda/fast_gelu_impl.cu
operators/contrib/cuda/utils.cuh
operators/tokenizer/bpe_decoder.hpp
operators/tokenizer/bpe_kernels.cc
operators/tokenizer/sentencepiece_decoder.hpp
operators/tokenizer/sentencepiece_tokenizer.cc
operators/tokenizer/trie_tokenizer.hpp

Refactor ORT-Extension for the coming GroupQueryAttention work (https://github.com/microsoft/onnxruntime-extensions/pull/654).
Main changes:
- separate common macros to a new header
- separate other ORT dependencies than custom ops to a new header
- cublas and device id info in cuda context
- separate cuda type (MFloat16, etc.) to a new header
- separate cuda device properties to a new header

refactor ORT-Extension for the coming GroupQueryAttention work

---

operators/tokenizer/bpe_kernels.h
operators/tokenizer/bpe_streaming.hpp

https://github.com/microsoft/onnxruntime-extensions/blob/c58c930739ffa481744d59a3e170895e1461b9b4/operators/tokenizer/bpe_streaming.hpp#L34 is expecting a reference, but the function does not return a reference resulting in a compiler error.
This PR addresses this issue.

Return added_tokens_ by reference

---

include/custom_op/tensor_api.h

Fix warnings like this:
```
D:/Android/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/memory:2427:5: warning: delete called on 'Ort::Custom::IStringTensorStorage<std::basic_string_view<char>>' that is abstract but has non-virtual destructor [-Wdelete-abstract-non-virtual-dtor]
delete __ptr;
^
...
D:/Android/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/memory:2427:5: warning: delete called on 'Ort::Custom::ITensorStorage' that is abstract but has non-virtual destructor [-Wdelete-abstract-non-virtual-dtor]
delete __ptr;
```
Cleanup virtual/override usage. 
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-override
https://github.com/isocpp/CppCoreGuidelines/pull/1448

Fix warnings around usage of virtual.

---

java/build.gradle

The Java module system (introduced in Java 9) requires that all modules on the module path have unique names, and the current name for ORT-extensions collides with ORT as both use `com.microsoft.onnxruntime`. This PR changes the ORT-extensions module name to `com.microsoft.onnxruntime.extensions` to remove the collision.
If they are colliding then work needs to be done in the user's build system to pull ORT-extensions off from the module path and put it on the classpath which can be irritating to do particularly if it's consumed by a third party dependency which might not be doing a module aware build.

[java] Setting Java module name to com.microsoft.onnxruntime.extensions

---

.pipelines/android_packaging.yml
.pipelines/ios_packaging.yml
.pipelines/templates/android-shared-lib-build.yml
.pipelines/templates/build-package-for-linux.yml
.pipelines/templates/build-package-for-nuget.yml
.pipelines/templates/build-package-for-windows.yml
.pipelines/templates/component-governance-component-detection-steps.yml
.pipelines/templates/ios-framework-build.yml
.pipelines/templates/mac-shared-lib-build.yml
cgmanifest.json
cmake/externals/sentencepieceproject.cmake
java/build.gradle

Fix component governance warnings:
- update protobuf version being used by sentencepiece and the java tests
- ignore unused language bindings from protobuf and triton
- specify the CG config file with ignored directories where required
Fix cgmanifest.json:
- 'git' entries require a commit hash not version
- use 'other' for opencv third party code that is included directly in the opencv repo
- the path isn't a valid repositoryUrl value to be provided as a 'git' entry
- update version numbers/commit hashes to match the latest code

Fix component governance issues.

---

.pipelines/ci.yml
.pipelines/ci_optional.yml
.pipelines/wheels_linux.yml
CMakeLists.txt
docs/custom_ops.md
tools/test_cibuildwheel.bat
tools/test_cibuildwheel.sh

The current Triton dependency introduced by these operations does not meet Microsoft's latest security requirements. Therefore, these operators will be removed from all pipelines.

disable azure ops from ci/packaging pipelines

---

.pipelines/ci.yml
.pyproject/cmdclass.py
CMakeLists.txt
build.bat
cmake/ext_cuda.cmake
cmake/externals/opencv-no-rtti.patch
requirements-dev.txt

inspired by this PR: https://github.com/microsoft/onnxruntime/pull/21004

Fix the pipeline breaks dues to the MSVC 19.40 and numpy 2.0 release

---

include/ort_c_to_cpp.h
shared/api/image_processor.cc
shared/api/runner.hpp

* warning C5038: data member 'ort_extensions::ImageProcessor::allocator_' will be initialized after base class 'OrtxObjectImpl'
* warning C5038: data member 'ort_extensions::OrtxRunner::allocator_' will be initialized after data member 'ort_extensions::OrtxRunner::ops_'

Fix several C5038 warnings

---

cgmanifest.json
cmake/externals/pybind11.cmake

v2.12 is the latest and it claims support both version of numpy.

upgrade pybind11 2.12 to support both numpy 1.x and 2.x

---

.pipelines/templates/build-package-for-linux.yml
.pipelines/templates/build-package-for-nuget.yml

The old pool uses Ubuntu 20.04.
The new pool uses Ubuntu 22.04.
We are retiring the old one.

Switch aiinfra-Linux-CPU machine pool to onnxruntime-Ubuntu2204-AMD-CPU

---

.pipelines/ios_packaging.yml

Increases timeout from 120 -> 150 minutes to resolve pipeline timeout issues in preparation for ORT 1.19 release.

increase timeout for iOS CI Pipeline

---

.pipelines/ios_packaging.yml

Increases timeout from 150 -> 180 minutes to resolve pipeline timeout issues in preparation for ORT 1.19 release.

increase timeout even more for iOS Packaging Pipeline

---

tools/android/package_ops.config

Fix for extensions.android_packaging pipeline in preparation for ORT 1.19 release.

removes OpenAIAudioToText from config

---

operators/tokenizer/bpe_decoder.hpp
operators/tokenizer/bpe_streaming.hpp
test/test_cliptok.py
test/test_fast_tokenizer.py

Missing the special handling on SentencePiece converted tokenizer in BPEDecoder.

Fix spm converted FastTokenizer issue on non-ascii char

---

.pipelines/templates/esrp_nuget.yml
.pipelines/templates/win-esrp-dll.yml

Upgrade ESRP signing task from v2 to v5 because 'OnnxRuntime CodeSign 20190817' doesn't exist anymore.
Configuration is copied from this PR: https://github.com/microsoft/onnxruntime/pull/20995

Upgrade ESRP signing task from v2 to v5 

---

.pipelines/ios_packaging.yml
.pipelines/templates/build-package-for-ios-cocoapods.yml
nuget/DummyNativeNuget.nuspec
nuget/NativeNuget.nuspec
nuget/targets/net6.0-ios/Microsoft.ML.OnnxRuntime.Extensions.targets
tools/android/build_aar.py
tools/ci_build/extract_nuget_files.ps1
tools/ios/assemble_pod_package.py
tools/ios/build_xcframework.py

Refactor framework directory structure for MacOS packages
Apple started enforcing specific [framework structure](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html) for MacOS packages. We need to change how we package for MacOS to follow the guidelines

 Update macosx framework packaging to follow apple guidelines

---

.pipelines/templates/win-esrp-dll.yml

same as https://github.com/microsoft/onnxruntime/pull/21854.
The default keycode is test code sign.
KeyCode must be specified explicitly.

Sign dlls with the correct key code

---

.pipelines/templates/win-esrp-dll.yml

Files signature validation after signed by ESRP.
Add validation after the ESRP process.
Make sure the targeting pattern/suffix files are signed successfully by ESRP.
If the signature is not Valid, then will fail the following stages.
same as https://github.com/microsoft/onnxruntime/pull/21949

Add Files Signature Validation after Signed by ESRP

---

cmake/externals/opencv-no-rtti.patch
tools/build.py

We need the image decode/encode operators in the nuget package.

Don't disable vision operators in a catalyst build.

---

operators/tokenizer/bpe_kernels.cc
operators/tokenizer/bpe_utils.hpp
test/pp_api_test/test_tokenizer.cc

Currently, our regular expression pattern matching for BPE tokenization only supports the GPT2 regex.
This PR adds the following functionality:
1. Standard library regex support.
2. Llama3 regex support.
3. Custom regex implementation that will use appropriate regex given a model.

Add C++ regex support for Llama3, Standard Library, and Custom Cases

---

CMakeLists.txt

In #800 zlib source code was directly included. No need to link against zlib. This causes failure on Windows where zlib is not available globally.

Rm zlib when linking ocos_operators

---

operators/tokenizer/bpe_utils.hpp

Fixes prefast warning due to "gsl::span or std::string_view created from a temporary will be invalid when the temporary is invalidated (gsl.view)" issue from RegexMatchSTD.

Fix regex prefast warning

---

cmake/ext_apple_framework.cmake

Cherry pick for release-0.13
Ref: https://github.com/microsoft/onnxruntime-extensions/issues/825
"com.microsoft.onnxruntime_extensions" is not a valid identifier. Update it to "com.microsoft.onnxruntime-extensions"

Change the framework bundle identifier to a valid one (#829)

---

shared/api/image_transforms.hpp

This PR fixes a prefast issue in image transforms that caused the following error on certain machines due to list iterators for temporary objects: `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\list(194) : Assertion failed: list iterators incompatible`, specifically for transforms using interpolation.

Fix prefast issue in image transforms

---

operators/vision/decode_image.hpp
shared/api/image_transforms.hpp
test/pp_api_test/test_imgcodec.cc

_"WIN32 is a name that you could use and even define in your own code and so might clash with Microsoft's usage. _WIN32 is a name that is reserved for the implementor (in this case Microsoft) because it begins with an underscore and an uppercase letter - you are not allowed to define reserved names in your own code, so there can be no clash."_

fix the win32 macro usage

---

operators/vision/encode_image.hpp
operators/vision/image_encoder_darwin.hpp

Follow-up of #848. This fixes a native C++ crash.

Fix image encoder status

---

tools/ci_build/github/azure-pipeline/templates/windows-build-stage.yml
tools/ci_build/github/azure-pipeline/wheels_linux.yml
tools/ci_build/github/azure-pipeline/wheels_macos.yml

1 Publish whl Files to ORT-Nightly Feed:
2 For these 3 pipelines, official, linux wheel and macro wheel, upgrade Python version to 9,10,11,12,13 instead of 8,9,10,11,12.

Pipeline - Publish whl Files to ORT-Nightly Feed

---

cgmanifest.json
cmake/externals/dr_libs.cmake

See: https://github.com/microsoft/onnxruntime-genai/pull/861

Update dr_libs for better ARM64EC support

---

operators/vision/decode_image.hpp

To fix the following build error with GCC 14:
https://github.com/microsoft/onnxruntime-genai/actions/runs/12696859543/job/35391825241

Update decode_image.hpp: add missing header file

---

CMakeLists.txt

CMake's [target_link_libraries](https://cmake.org/cmake/help/latest/command/target_link_libraries.html#id2) function accepts plain library name(like re2) or target name(like re2::re2) or some other kinds of names. "plain library names" are old-fashioned, for compatibility only. We should use target names.
Similar to https://github.com/microsoft/onnxruntime/pull/23173

Fix re2 link

---

cmake/externals/json.cmake
operators/tokenizer/tokenizer_jsconfig.hpp

This commit removes the .release() calls, ensuring that CreateLiteCustomOpV2 now returns std::shared_ptr, maintaining proper smart pointer ownership and preventing memory corruption.

Update op_def_struct.h to fix memory leak

---

operators/tokenizer/bpe_kernels.cc
operators/tokenizer/tokenizer_jsconfig.hpp
test/data/added-tokens/tokenizer.json
test/data/added-tokens/tokenizer_config.json
test/pp_api_test/test_tokenizer.cc

Fixes tokenizer issue where special tokens added into `added_tokens_decoder` attribute in `tokenizer_config.json` but missing in `added_tokens` in `tokenizer.json` are still populated correctly into added tokens map such that they are not tokenized incorrectly. This ensures compatibility even with HuggingFace models whose files have inconsistent `tokenizer.json` and `tokenizer_config.json` files.
Validation

Add missing tokens from added_tokens_decoder into added_tokens

---

shared/api/speech_features.hpp

Fixes issue where user was getting vague error when using audio file with 48k Hz sampling rate: https://github.com/microsoft/onnxruntime-extensions/blob/0d5aefa9b2e3c0be57ba3ae2d872b920d6d494a6/include/ort_c_to_cpp.h#L109

Add check for audio sampling rate other than 8k or 16k Hz

---

operators/audio/audio_decoder.cc
shared/api/c_api_feature_extraction.cc

1. report explicit error if file format not recognizing.
2. report explicit error if the audio file not loaded.
related issue #900

Enhance error message on audio file processing

---

shared/api/runner.hpp
shared/api/speech_features.hpp
test/pp_api_test/test_feature_extraction.cc

replace the audio_frame tensor with an attention mask to better align with origin Python preprocessing

Support audio attention mask for multiple audio file preprocessing of Phi4 model

---

ThirdPartyNotices.txt
cgmanifest.json
cmake/externals/dlib.cmake
operators/tokenizer/bpe_kernels.cc
operators/tokenizer/tokenizer_jsconfig.hpp

remove _json_pointer usage since it would be deprecated in the release and causes some compiler warning in g++

fix the json_pointer compiler warnings within its latest release

---

operators/tokenizer/bpe_streaming.hpp

The added tokens weren't supported on SentencePiece converted tokenizer before.

Fix the added token decoding issue on spm based tokenizer

---

CMakeLists.txt

Addressing warning:
```
CMake Warning (dev) at onnxruntime_extensions-src/CMakeLists.txt:447:
Syntax Warning in cmake code at column 90
Argument not separated from preceding token by whitespace.
```

Remove comma in cmake argument list

---

shared/api/chat_template.cc

Fix warning:
shared\api\chat_template.cc(13,40): warning C4101: 'e': unreferenced local variable

Fix unreferenced variable warning in chat_template.cc

---

operators/tokenizer/ugm_kernels.hpp

This PR fixes a couple issues in UGM Kernels (used for our Marian tokenizer for the Marian translation model)
1. **Incorrect Spacing from Wrongful Comparisons due to Overflow**: In certain instances Id2Token may have run into an index for an escape sequence which was a very large number (`size_t(-1)`) and a unchecked comparison such as `pos + 3 == token.length()` which should end up being false in intention, was resulting in true due to overflow (i.e., `npos + 3` wraps around and accidentally equals `token.length()` for some short strings like "г").
2. **Titlecase Logic**: basic `toupper` does not work for a lot of languages, such as Russian, due to characters such as the Cyrillic ones. We hence refactor titlecase logic completely. Note that we use `std::towupper`, and although it would …

Fix Marian Decoding

---

.pipelines/ci.yml
requirements-dev.txt

1. Makes python version explicit for LinuxPyDbg
2. Enables download from registry
3. Adds pyreadline3 to requirements-dev.txt

Fix LinuxPyDbg in CI Pipeline

---

operators/tokenizer/bpe_streaming.hpp

Currently, the ORT Extensions BPE decoder _always_ skips special tokens, however this may not always be desired.

Avoid always Skipping Special Tokens when Decoding

---

include/ortx_tokenizer.h
operators/tokenizer/bpe_streaming.hpp
operators/tokenizer/ugm_kernels.hpp
shared/api/c_api_tokenizer.cc
shared/api/tokenizer_impl.cc
shared/api/tokenizer_impl.h
test/pp_api_test/test_tokenizer_chat.cc

Inside the foundry catalog for [Foundry Local](https://github.com/[microsoft/Foundry-Local](https://github.com/microsoft/Foundry-Local)), all tool call tokens are marked as special such that we can use them with guidance inside [GenAI](https://github.com/microsoft/onnxruntime-genai). Now, in order for decoding to work with these tokens, we need to expose using special tokens as an option in our Decoder API in Extensions. Hence, this API adds `skip_special_tokens` to `OrtxDetokenize1DWithOptions`, used in the GenAI `OgaDecoder`.
Note that we leave `OrtxDetokenize1D` as is for backward compatibility. In the future, we shall be adding an extensible options map API that will reduce the need for messy parameter additions to our Encoder/Decoder APIs, and can be easily consumed by GenAI and …

Add `skip_special_tokens` to Decoder API

---

operators/tokenizer/bpe_utils.hpp
test/data/nvidia-mistral/tokenizer_config.json
test/pp_api_test/test_tokenizer_impl.cc

This PR adds support for `nvidia/Mistral-NeMo-Minitron-8B-Instruct` tokenization and detokenization.
The regex pattern from the official tokenizer.json file for the model here: [tokenizer.json · nvidia/Mistral-NeMo-Minitron-8B-Instruct at main](https://huggingface.co/nvidia/Mistral-NeMo-Minitron-8B-Instruct/blob/main/tokenizer.json):
`[^\r\n\p{L}\p{N}]?[\p{Lu}\p{Lt}\p{Lm}\p{Lo}\p{M}]*[\p{Ll}\p{Lm}\p{Lo}\p{M}]+|[^\r\n\p{L}\p{N}]?[\p{Lu}\p{Lt}\p{Lm}\p{Lo}\p{M}]+[\p{Ll}\p{Lm}\p{Lo}\p{M}]*|\p{N}|?[^\s\p{L}\p{N}]+[\r\n/]*|\s*[\r\n]+|\s+(?!\S)|\s+`
is different from the official Mistral one here: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Base-2503/blob/main/tokenizer.json:
`(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\r\n\p{L}\p{N}]?\p{L}+|\p{N}{1,3}| …

Add Nvidia Mistral Support
