microsoft/onnxruntime-extensions

docs/custom_text_ops.md
This PR includes:
- operator schema for text processing ops
We need a deep discussion of the operator schema. Any suggestion and issues are welcome~
=> Operator Schemas of text processing ops

ocos/kernels/string_length.cc, ocos/kernels/string_length.hpp, shared/ortcustomops.cc, test/test_string_length.py
=> Add StringLength op

ocos/kernels/string_common.cc, ocos/kernels/string_common.h, ocos/kernels/ustring.cc, ocos/kernels/ustring.hpp, test/shared_test/test_ortops.cc, test/static_test/test_base64.cc, test/static_test/test_base64.h, test/static_test/test_strings.cc, test/static_test/test_strings.h, test/static_test/test_ustring.cc, test/static_test/test_utils.cc, test/static_test/test_utils.h
- Wrap u32string with ustring, in case we will use other implementation in the future
=> add unicode support by u32string

docs/custom_text_ops.md, ocos/kernels/string_concat.cc, ocos/kernels/string_concat.hpp, ocos/kernels/string_length.cc, shared/ortcustomops.cc, test/test_string_concat.py, test/test_string_length.py
- add a new operator --- StringConcat
=> Add Operator StringConcat

includes/onnxruntime/onnxruntime_cxx_inline.h, tokenizer/sentencepiece_tokenizer.cc
#80 does not work with onnxruntime 1.7.0.
=> Fixes onnxruntime C API 5 forward compatibility

README.md, onnxruntime_customops/__init__.py
Signed-off-by: xavier dupré <xavier.dupre@gmail.com>
=> Upgrade version number to 0.0.2

.gitignore, .gitmodules, CMakeLists.txt, ci_build/azure-pipelines/mshost.yaml, setup.py, tokenizer/gpt2_tokenizer.cc
=> Create webassembly pipeline 

ci_build/onnxruntime_integration/build_with_onnxruntime.sh, ci_build/onnxruntime_integration/onnxruntime_v1.8.patch
Update patch file to integrate CustomOps into ONNXRuntime.
=> Update patch file to integrate CustomOps into ONNXRuntime.

operators/math/segement_extraction.cc
Fix a bug of SegmentExtraction
=> Fix a bug of SegmentExtraction

operators/tokenizer/bert_tokenizer_decoder.cc, operators/tokenizer/bert_tokenizer_decoder.hpp
- Replace the memory through replacing ustring by std::string_view in BertTokenizerDecoder
=> Reduce memory usage

docs/custom_text_ops.md, operators/tokenizer/basic_tokenizer.cc
- Add docs for new operators
- BasicTokenizer
- BertTokenizer
- BertTokenizerDecoder
- StringECMARegexReplace
=> Add doc for new operators

onnxruntime_extensions/pnp/_nlp.py
Issue #230: Add HuggingFace vocab format to Bert tokenizer
HuggingFace vocab format is newline separated (unlike GPT which is
json). Newline separated is likely to be faster and doesn't require
an external library to parse it. Instead of introducing a json based
format, added support for native HuggingFace newline separated token
format.
=> Issue #230: Add HuggingFace vocab format to Bert tokenizer

.config/tsaoptions.json, .pipelines/OneBranch.PullRequest.yml, ci_build/policheck_exclusions.xml, setup.py
For compliance work. This is just the start.
=> Create onebranch pipeline for win32-wheel

.pipelines/OneBranch.Official.yml
The new OneBranch.Official.yml is the main branch.
The existing [OneBranch.PullRequest.yml](https://github.com/microsoft/onnxruntime-extensions/blob/main/.pipelines/OneBranch.PullRequest.yml) is for pull requests.
Official package will need be generated from the build jobs in OneBranch.Official.yml.
The two yaml files are almost identical, except they are extended from different base files and serve different purposes.
=> Add OneBranch.Official.yml

onnxruntime_extensions/pnp/_nlp.py
Issue #230: Fix argument handling in BertTokenizer
Fixed argument handling in pnp where the arguments weren't being passed
down to the tokenizer as expected.
=> Issue #230: Fix argument handling in BertTokenizer

onnxruntime_extensions/pnp/__init__.py, onnxruntime_extensions/pnp/_nlp.py, onnxruntime_extensions/pnp/_torchext.py, operators/tokenizer/bert_tokenizer.cc, operators/tokenizer/bert_tokenizer.hpp, operators/tokenizer/tokenizers.cc, tutorials/hf_bert_e2e.py
Issue #226: Functional e2e NLP example
* Implemented a new version of Kernel and the CustomOp to support
output that matches the HuggingFace model's input without the need
for intermediate python logic.
* Implemented a e2e tutorial for exporting and inferencing using the
HuggingFace's QuestionAnswering model.
Known Issue: Python side doesn't have an implementation of Bert Decoder
and so the augmented model is only half-complete. At the time of
inferencing the HuggingFace tokenizer is used to decode the result back
to string.
=> Issue #226: Functional e2e NLP example

.az/mshost.yaml, README.md, build_matrix.md, includes/onnxruntime/onnxruntime_c_api.h, includes/onnxruntime/onnxruntime_cxx_api.h, includes/onnxruntime/onnxruntime_cxx_inline.h, requirements-dev.txt, test/test_torch_ops.py
Update workflow matrix
Update workflow matrix so it's consistent across the platforms and using
newer versions of the dependencies. Current supported matrix -
Python | 3.7 | 3.8 | 3.9 | 3.10
---|---|---|---|---
Onnxruntime | 1.9.0 (Sept 22, 2021) | 1.10.0 (Dec 7, 2021) | 1.11.0 (Mar 26, 2022) | 1.12.1 (Aug 4, 2022)
Torch | 1.9.1 (Sept 22, 2021) | 1.10.0 (Oct 21, 2021) | 1.11.0 (Mar 10, 2022) | 1.12.1 (Aug 5, 2022)
TorchVision | 0.10.1 (Jun 15, 2021) | 0.11.1 (Oct 21, 2021) | 0.12.0 (Mar 10, 2022) | 0.13.1 (Aug 5, 2022)
TorchAudio | 0.9.0 (Jun 15, 2021) | 0.10.0 (Oct 21, 2021) | 0.11.0 (Mar 10, 2022) | 0.12.1 (Aug 5, 2022)
Release versions strictly follow the convention of onnxruntime being one
release ahead of all its dependencies.
=> Update workflow matrix

operators/text/string_ecmaregex_split.hpp
Fix TSA Issue #1908153 & #1908163
=> Fix TSA Issue #1908153 & #1908163

onnxruntime_extensions/pnp/_nlp.py
Missing check for existence of attribute before accessing - added.
Validation
=> Fixed attribute not found issues for hf_bert_tokenizer

onnxruntime_extensions/_cuops.py, operators/tokenizer/blingfire_sentencebreaker.cc, operators/tokenizer/sentencepiece_decoder.hpp, operators/tokenizer/sentencepiece_tokenizer.hpp, operators/tokenizer/tokenizers.cc, test/test_sentencepiece_ops.py
Need support the special token as well, which will be a different PR.
=> a naive decoder for sentencepiece tokenization

README.md, requirements-dev.txt
[transformer 4.25 broken on pytorch 1.9/1.10
=> Fix ci pipelines failure caused by the latest transformer package

docs/custom_ops.md, test/test_pyops.py, test/test_sentencepiece_ops.py, test/test_string_ops.py, tutorials/tf2onnx_custom_ops_tutorial.ipynb
=> Use `object` instead of `np.object` and `str` instead of `np.str`.

setup.py, tools/get_vsdevcmd.ps1
The fixing solves the problem of the removal build-id from release build, while it should be kept in nightly build.
=> port the fixing from the release branch

.github/workflows/gradle-wrapper-validation.yml, java/gradle/wrapper/gradle-wrapper.properties, java/src/test/android/gradle/wrapper/gradle-wrapper.properties
- Add github workflow to validate gradle-wrapper.jar checksums
- Add checksum for existing gradle wrapper distributions
=> Gradle wrapper security updates

operators/tokenizer/roberta_tokenizer.cc
Use byte list in bpe algorithm to determine post-bpe token lengths for offset mapping.
=> Improve offset map algorithm for RobertaTokenizer

operators/tokenizer/roberta_tokenizer.cc
Fixed AB#13994 
https://aiinfra.visualstudio.com/ONNX%20Runtime/_workitems/edit/13994/
=> Fix size_t overflow issue for RobertaTokenizer

tutorials/whisper_e2e.py
This PR makes the Whisper E2E script more portable for other environments.
=> Make Whisper E2E script more portable

.pipelines/templates/build-package-for-ios-cocoapods.yml, .pipelines/templates/ios_shared_lib_build.yml, tools/ios/build_xcframework.py
One way to address PR comment: https://github.com/microsoft/onnxruntime-extensions/pull/408#discussion_r1180872453
=> Get the iOS xcframework build working with the split build/pack approach.

.pipelines/templates/build-package-for-linux.yml
Fixes: https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=309891&view=logs&j=37dbdb68-095e-55bf-d24c-0e070abe6be8&t=c715c394-b91d-54b5-b7f3-0850f6af32e9
=> Upgrade CMake for Linux NuGet packaging pipeline

.pipelines/ci.yml
Disable Azure op build due to shaky triton.
=> Disable Azure op build

.pipelines/android_packaging.yml, .pipelines/ci.yml, .pipelines/ios_packaging.yml, .pipelines/wheels_macos.yml
=> Update ci.yml for Azure Pipelines

.pipelines/OneBranch.Official.yml, .pipelines/OneBranch.PullRequest.yml, .pipelines/wheels_linux.yml, operators/azure/azure_invokers.cc, operators/azure/azure_invokers.hpp
Assemble file name for azure audio.
=> Assemble file name for azure audio

.pipelines/templates/build-package-for-windows.yml
Change the machine pool from Win-CPU-2021 to onnxruntime-Win-CPU-2022
=> Update build-package-for-windows.yml: change machine pool

CMakeLists.txt, test/test_audio_signal.py, tools/gen_selectedops.py
and with some minor doc string fixes
=> Add the new operators in cmake flags files.

docs/custom_ops.md
Add details to Azure ops documentation.
=> Add details to Azure ops documentation

onnxruntime_extensions/_hf_cvt.py, test/test_autotokenizer.py
For WSSI work as requested by Ran.
=> Close gap in vocab for AutoTokenizer support for GPT4Tokenizer

tutorials/pytorch_custom_ops_tutorial.ipynb
https://github.com/microsoft/onnxruntime-extensions/blob/main/tutorials/pytorch_custom_ops_tutorial.ipynb 
#PingMSFTDocs
=> Typo "Pytorch"→"PyTorch"

.pipelines/android_packaging.yml, .pipelines/ci.yml, .pipelines/templates/android-shared-lib-build.yml, .pipelines/templates/build-package-for-android-aar.yml, .pipelines/templates/build-package-for-nuget.yml, java/build.gradle
- Update JDK version to 17 in build definitions.
- Update com.diffplug.spotless to 6.22.0.
=> Fix Android CI build issues

base/ustring.h, includes/onnxruntime_customop.hpp, onnxruntime_extensions/_hf_cvt.py, operators/tokenizer/bpe_decoder.hpp, operators/tokenizer/bpe_kernels.cc, operators/tokenizer/bpe_kernels.h, operators/tokenizer/bpe_tokenizer.hpp, operators/tokenizer/bpe_utils.hpp, operators/tokenizer/tokenizers.cc, operators/tokenizer/trie_tokenizer.hpp, operators/tokenizer/trietree.hpp, test/test_autotokenizer.py
1. added_token attribute, which is similar to HF's tokenizer
2. BPE code refactoring for status return style.
3. some minor issues fixing.
=> Support 'added_token' attribute for BPE tokenizer and some code refactoring.

onnxruntime_extensions/tools/add_pre_post_processing_to_model.py
I'm only learning onnxruntime extension but this seems to me like a typo.
=> Fixed a bug (typo) in yolo_detection

.pipelines/ci.yml
update WIN/Linux CPU pools to onnxruntime custom pools.
update CPU_NUM from 2 to 8
=> Update CPU pool to custom pool

onnxruntime_extensions/tools/add_pre_post_processing_to_model.py
Run strict shape inferencing and save the model without the unnecessary ValueInfo entries.
=> Better update to YOLO post-processing addition

includes/custom_op_lite.h
=> Add some API forwards compatibility

.gitignore, .pyproject/backend.py, .pyproject/cmdclass.py, .pyproject/setup_cmds.py, docs/development.md, onnxruntime_extensions/__init__.py, onnxruntime_extensions/_ocos.py, pyproject.toml, setup.py, test/cuda/test_cudaops.py
1. Add an argument on build python package for CUDA
2. Add a unit test for CUDA operator.
=> Enhancing CUDA Support in Python Package Build and Testing

.pyproject/cmdclass.py, CMakeLists.txt
for sake of the cherry-pick for release branch, the previous PR needs to be split.
=> fix the unit test flag issue on packaging pipelines

onnxruntime_extensions/_hf_cvt.py, onnxruntime_extensions/_torch_cvt.py, test/test_whisper.py
=> using the huggingface whisper config instead of fixed numbers

nuget/DummyNativeNuget.nuspec, nuget/NativeNuget.nuspec, nuget/targets/netstandard/Microsoft.ML.OnnxRuntime.Extensions.props
Hopefully last set of fixes.
Validation run going on: https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=423749
=> More Nuget pipeline fixes

base/base64.h, includes/onnxruntime_customop.hpp
=> Add the cstdint header for GCC 13

.pipelines/OneBranch.Official.yml
For fixing a build error.
The change is similar to https://github.com/microsoft/onnxruntime/pull/19293
=> Update OneBranch.Official.yml for Azure Pipelines

nuget/DummyNativeNuget.nuspec, nuget/NativeNuget.nuspec
Dummy/Extensions nuspec changes for catalyst variant.
=> Nuget package changes for catalyst extensions

cmake/ext_cuda.cmake, docs/How_to_write_custom_op.md, include/custom_op/custom_op_lite.h, include/op_def_struct.h, onnxruntime_extensions/__init__.py, operators/cuda/attention_lib/flash_attention/flash.h, operators/cuda/attention_lib/flash_attention/flash_api.cc, operators/cuda/attention_lib/flash_attention/flash_api.h, operators/cuda/attention_lib/flash_attention/flash_fwd_kernel.h, operators/cuda/attention_lib/flash_attention/flash_fwd_launch_template.h, operators/cuda/attention_lib/flash_attention/softmax.h, operators/cuda/attention_lib/flash_attention/utils.h, requirements-dev.txt
sync to flash attention kernel 2.5.9 and add document of how to write custom op
=> sync to flash attention kernel 2.5.9 and add document of how to write custom op

tools/ci_build/extract_nuget_files.ps1
Description
Update nuget extraction path for iOS xcframework to correct directory
Motivation and Context
Fix nuget packaging pipeline
=> Update nuget extraction path for iOS xcframework

cmake/ext_apple_framework.cmake
Ref: https://github.com/microsoft/onnxruntime-extensions/issues/825
"com.microsoft.onnxruntime_extensions" is not a valid identifier. Update it to "com.microsoft.onnxruntime-extensions".
cc @wenbingl @edgchen1
=> Update the framework bundle identifier to a valid bundle ID

shared/api/tokenizer_impl.cc, shared/api/tokenizer_impl.h, test/pp_api_test/test_tokenizer.cc
And stop the test if the tokenizer cannot be loaded.
=> Validate the tokenizer class name on data loading

operators/vision/image_decoder_win32.hpp
=> Improve WIC error reporting

tools/ci_build/github/azure-pipeline/templates/windows-build-stage.yml
Extend timeout for always failed job.
=> Fix Pipeline Timeout Issue

operators/tokenizer/bpe_kernels.cc, operators/tokenizer/bpe_kernels.h, operators/tokenizer/bpe_streaming.hpp, operators/tokenizer/bpe_tokenizer_model.hpp, operators/tokenizer/tokenizer_common.h, operators/tokenizer/tokenizer_jsconfig.hpp, shared/api/image_transforms_phi_4.hpp, shared/api/runner.hpp, shared/api/speech_extractor.cc, test/pp_api_test/test_feature_extraction.cc, test/pp_api_test/test_processor.cc, test/pp_api_test/test_tokenizer.cc, test/test_pp_api.py
Also revert image_size data type change.
=> Support left and right strip for Added token

operators/tokenizer/tokenizer_jsconfig.hpp
Addresses https://github.com/microsoft/onnxruntime-genai/issues/1262
=> Read the tokenizer config using path.open to support special characters

.pipelines/ci.yml, .pipelines/ci_optional.yml
1.The windows image has been updated to ORT's version.
2.Remove the python dependency on conda, fully rely on Python standalone package.
=> Fix the CI pipeline issues with latest agent pool images.

shared/api/chat_template.cc, shared/api/tokenizer_impl.h
- Adds chat template support for `google/gemma-3-1b-it`, `google/gemma-3-4b-it`, `google/gemma-3-12b-it`, and `google/gemma-3-27b-it`
- Fixes minor issue with Phi-3/Phi-3.5 chat templates.
=> Add Gemma-3 Chat Template Support

.pipelines/ci.yml
=> try to fix the ci pipeline failure on Linux/MacOS

onnxruntime_extensions/cvt.py
This PR makes imports for transformers and tokenizers lazy in `cvt.py`.
With #860 support for huggingface-embedded json tokenizers was added. With this change, transformers is trying to be imported, but transformers itself is an optional dependency of onnxruntime-extensions.
As `cvt.py` is imported at the top-level and several model conversions e.g., `yolo` don't require transformer dependencies, we should guard the import.
@sayanshaw24 Could you please review? Please let me know, if anything is missing 👍 
closes #921.
=> fix: lazy import of hf transformers in cvt 🐞

operators/tokenizer/bpe_streaming.hpp, operators/tokenizer/bpe_tokenizer_model.hpp, shared/api/tokenizer_impl.cc, test/data/phi-4-base/tokenizer_config.json, test/pp_api_test/test_tokenizer_chat.cc
Fixes Phi-4 model quality issues due to incorrect encoding and decoding of chat template tokens.
=> Update Tokenizer and Detokenizer for Chat Template Tokenization

.pipelines/templates/esrp_nuget.yml, .pipelines/templates/win-esrp-dll.yml, tools/ci_build/github/azure-pipeline/templates/esrp_nuget.yml, tools/ci_build/github/azure-pipeline/templates/win-esrp-dll.yml
=> Update ESRP parameter

shared/api/chat_template.cc, test/test_pp_api.py
For Qwen, and some other models, `tools` should be a list of functions stored in JSON format, passed in separately, as an additional input to `apply_chat_template`. These tools were not handled correctly in the C++ backend in ApplyChatTemplate and were leading to extra newlines. This is now fixed by this PR.
=> Fix Tools Usage for Chat Templates
